version: "1"
services:
  blog:
    stdin_open: true
    tty: true
    volumes:
      - ".:/app"
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    # command: bundle exec jekyll s -H 0.0.0.0
    command: sh -c "bundle install && bundle exec jekyll s -H 0.0.0.0"
    ports:
      - 4000:4000
